version: '2.1'
orbs:
 # import CircleCI's aws-cli orb
 aws-cli: circleci/aws-cli@3.1
jobs:
 aws-example:
   docker:
     - image: cimg/aws:2022.06
   steps:
     - checkout
     # run the aws-cli/setup command from the orb
     - aws-cli/setup:
         role-arn: 'arn:aws:iam::919512924188:role/circle_ec2_deployment'
         aws-region: AWS_REGION
     - run:
         name: Log-into-AWS-ECR
         command: |    
           aws ecr get-login-password 
workflows:
 OIDC-with-AWS:
   jobs:
     - aws-example:
         context: aws
